### ISSUE TITLE
setting maxUnitOfTime to hours gives me an error

### ISSUE THREAD

**Issue by JoseGeorges8** [james-alex/date_time_format#5]
Hi!

Great package I was about to create a function to format the time like your `relative` function, but you have it!

However I can't seem to understand why I get this error when I try to set `maxUnitOfTime: UnitOfTime.hour`

This is the error:

```
The method '>' was called on null.
Receiver: null
Tried calling: >(0)

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      DateTimeFormat.relative.<anonymous closure> (package:date_time_format/src/date_time_format.dart:409:65)
#2      ListMixin.indexWhere (dart:collection/list.dart:496:15)
#3      DateTimeFormat.relative (package:date_time_format/src/date_time_format.dart:409:37)
#4      DateTimeFormatter.relative (package:date_time_format/src/date_time_extension_methods.dart:144:27)
```

And this is the code:

```
    print(dateTime); // 2021-01-05 22:01:43.000Z
    print(DateTime.now()); // 2021-01-06 19:29:04.152148

'${DateTime.now().relative(to: dateTime, round: false, appendIfAfter: 'left', levelOfPrecision: 2, maxUnitOfTime: UnitOfTime.hour)}';
```

If I remove the `maxUnitOfTime` works fine, but I'd rather not show the days if possible.

Thanks!

**Comment by james-alex** [comment]
Hello,

Thanks for reporting this bug. It's been fixed in `v1.1.1`, now on [pub.dev](https://pub.dev/packages/date_time_format).
